### ISSUE TITLE
Allocating memory to multiple GPUs

### ISSUE THREAD

**Issue by b2jia** [mritools/cupyimg#20]
Is there support in cupyimg to enable parallelism - especially if a large image cannot fit into the memory of one GPU card? Maybe this is a better question suited for CuPy, but I wonder if the authors have faced similar issues before?

Thank you,

-B

**Comment by grlee77** [comment]
As recently, added to the top-level [README](https://github.com/mritools/cupyimg/blob/master/README.md), I would recommend checking out [cuCIM](https://github.com/rapidsai/cucim) which is a new RAPIDS project that will be expanding the functionality started within `cupyimg.skimage` in this repository. To work with multiple GPUs I would recommend looking at combining cuCIM with [Dask](https://dask.org/).

Two potential use cases cuCIM + Dask + [dask-cuda](https://dask-cuda.readthedocs.io/en/latest/):
1.) serial block-wise processing of data to reduce peak memory requirements
2.) distributed parallel block-wise processing across multiple GPUs/nodes

At the moment there is no built-in Dask capability either here or in cuCIM, but Dask does already know how to work with CuPy arrays, so it can be done. The [dask-image](http://image.dask.org/en/latest/) repository has concrete implementations of functions from the `scipy.ndimage` API, some of which also support CuPy arrays (via CuPy's `cupyx.scipy.ndimage`). The same type of approaches (e.g. using Dask's `map_overlap`) can be applied to many functions in cuCIM.

**Comment by b2jia** [comment]
I see, thanks for this reference. Thought I'd ask, seeing this is probably a repo inspired by MRI image analysis. I find affine image registration very memory+time intensive using CPUs. However, not all images can be loaded into one GPU card. I will look at `dask-image`.
